@startuml

class Pokemon {
    name: str
    level: int
    type: str
    healthPoints: int
    powerPoints: int
    attack: int
    defence: int
    levelUp()
    evolve()
    battle()
    useMove()

}

class Pokedex {
    PokemonID: int
    PokemonWeight: int
    PokemonHeight: int
    PokemonLocation: str
    PokemonDescription: str
    callable()


}

class Trainer {
    name: str
    gender: str 
    badges: int
    pokemon: list 
    items: list 
    buyItem()
    catchPokemon()
    winBattle()
    looseBattle()

}

class Bike {
    velocity: const
    use()
    ride()

}
class Location {

}


class Settlement {
    buildings: int 
    goInBuilding()
    interactWithPeople()

}

class Map {
    location: list 
    callable()

}


class Item {
    price: int
    effect: str 
    ammount: int 
    useInBattle()
    useOutsideOfBattle()
}

class Building

class Route

class Potion 

class Pokeball


Trainer o--> Pokemon: owns

Trainer o--> Item: owns

Item <|-- Pokeball: type of 

Item <|-- Potion: type of 

Trainer *--> Map: owns

Trainer *--> Pokedex: owns

Trainer *--> Bike: owns

Trainer --> Settlement: can reach

Trainer --> Route: can reach

Map --> Settlement: displayed on

Map --> Route: displayed on 

Settlement <|-- Building: has 

Pokemon *--> Battle: do

Pokemon *--> Move: use 

Battle o--> Move: use

Move *--> VM: is type of (usable outside of Battle!)


@enduml
