@startuml

class Pokemon {
    name: str
    level: int
    type: str
    healthPoints: int
    powerPoints: int
    attack: int
    defence: int
    moves: list 
    levelUp()
    evolve()
    battle()
    useMove()
    useVM()

}

class Pokedex {
    PokemonID: int
    PokemonWeight: int
    PokemonHeight: int
    PokemonLocation: str
    PokemonDescription: str
    callable()

}

class Player {
    name: str
    gender: str 
    badges: int
    pokemon: list 
    items: list 
    buyItem()
    useItem()
    catchPokemon()
    winBattle()
    looseBattle()
    walk()

}

class NPC {
    priceMoney: int 
    interact()

}

class Bike {
    velocity: const
    ride()

}

class Location {
    hasWildPokemon: bool
    hasTrainerBattles: bool 

}

class Cave {
    darkness()
    PokemonBattle()

}

class Settlement {
    buildings: int 
    interactWithPeople()
    EnterBuilding()

}

class Map {
    location: list 
    playerOnMap()
    callable()

}

class Item {
    price: int
    effect: str 
    ammount: int 
    useInBattle()
    useOutsideOfBattle()
}

class Building {
    buildingType: str 

}

class Route {
    battle()

}

class Potion {
    heal: int 
    healsPokemon()
}

class Pokeball {
    catchrate: int 
    catchesPokemon()
}

class Pokemarket {
    sellsItems()

}

class Pokecenter {
    healsPokemon()
}

class Pokegym {
    fightTrainers()
}

class Pokeleague {
    fightTrainers()
}


Pokemon *--> Pokedex: displayed on

Player "1" o--> "0..6" Pokemon: owns / encounters

Player "1" o--> "0..n" Item: owns

Player "1" <|-- "n" NPC

NPC o--> Pokemon: can own 

Location *--> NPC: can be found 

Item <|-- Pokeball: type of 

Item <|-- Potion: type of 

Player "1" *--> "0..1" Map: owns

Player "1" *--> "0..1" Pokedex: owns

Player "1" *--> "0..1" Bike: owns

Player "1" --> "n" Location: can reach

Location "1" <|-- "1" Route: type of 

Location "1" <|-- "1" Settlement: type of 

Location "1" <|-- "1" Cave: type of 

Location *--> Map: displayed on

Settlement "1" <|-- "n" Building: has 

Building <|-- Pokemarket: type of 

Building <|-- Pokecenter: type of

Building <|-- Pokeleague: type of

Building <|-- Pokegym: type of


@enduml
